services:
  - type: web
    name: underleaf
    runtime: docker
    plan: free
    region: oregon
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: OAUTHLIB_INSECURE_TRANSPORT
        value: "0"
    healthCheckPath: /
    autoDeploy: true